# Describes the format for available Z-Wave services
add_node:
  description: Add a new node to the Z-Wave network.
  fields:
    secure:
      description: Add the new node with secure communications. Secure network key must be set, this process will fallback to add_node (unsecure) for unsupported devices. Note that unsecure devices can't directly talk to secure devices.
    instance_id:
      description: (Optional) The OZW Instance/Controller to use, defaults to 1.

remove_node:
  description: Remove a node from the Z-Wave network. Will set the controller into exclusion mode.
  fields:
    instance_id:
      description: (Optional) The OZW Instance/Controller to use, defaults to 1.

set_config_parameter:
  description: Set a config parameter to a node on the Z-Wave network.
  fields:
    node_id:
      description: Node id of the device to set config parameter to (integer).
      example: 10
    parameter:
      description: Parameter number to set (integer).
      example: 8
    value:
      description: Value to set for parameter. (String value for list and bool parameters, integer for others).
      example: 50268673
    instance_id:
      description: (Optional) The OZW Instance/Controller to use, defaults to 1.
