# https://dev.azure.com/home-assistant

trigger:
  branches:
    include:
    - dev
  tags:
    include:
    - '*'

variables:
  versionBuilder: '3.1'
  versionWheels: 'dev'


jobs:

- job: 'Wheels'
  condition: eq(variables['Build.SourceBranchName'], 'dev')
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    maxParallel: 2
    matrix:
      amd64:
        buildArch: 'amd64'
  steps:
  - script: sudo docker pull homeassistant/$(buildArch)-wheels:$(versionWheels)
    displayName: 'Install wheels builder'
  - script: |
      sudo docker run --rm -v $(pwd):/data:ro \
        homeassistant/$(buildArch)-wheels:$(versionWheels) \
        --apk "build-base;cmake;git;linux-headers;bluez-dev;libffi-dev;openssl-dev;glib-dev;eudev-dev;libxml2-dev;libxslt-dev;libpng-dev;libjpeg-turbo-dev;tiff-dev;autoconf;automake;cups-dev;linux-headers;gmp-dev;mpfr-dev;mpc1-dev;ffmpeg-dev" \
        --index https://wheels.hass.io \
        --requirement requirement_all.txt \
        --upload rsync \
        --remote wheels@wheels.hass.io:/opt/wheels
    displayName: 'Run wheels build'
