resume_program:
  description: Resume the programmed schedule.
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: 'climate.kitchen'
    resume_all:
      description: Resume all events and return to the scheduled program. This default to false which removes only the top event.
      example: true

set_fan_min_on_time:
  description: Set the minimum fan on time.
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: 'climate.kitchen'
    fan_min_on_time:
      description: New value of fan min on time.
      example: 5
