airflow_min:
  description: Set the airflow minimum percent for a zone
  fields:
    entity_id:
      description: iZone Zone entity
      example: "climate.bed_1"
    airflow:
      description: Airflow percent in 5% increments
      example: "95"
airflow_max:
  description: Set the airflow maximum percent for a zone
  fields:
    entity_id:
      description: iZone Zone entity
      example: "climate.bed_1"
    airflow:
      description: Airflow percent in 5% increments
      example: "95"
