persistent_notification:
  create:
    description: Show a notification in the frontend

    fields:
      message:
        description: Message body of the notification. [Templates accepted]
        example: Please check your configuration.yaml.

      title:
        description: Optional title for your notification. [Optional, Templates accepted]
        example: Test notification

      notification_id:
        description: Target ID of the notification, will replace a notification with the same Id. [Optional]
        example: 1234

homematic:
  virtualkey:
    description: Press a virtual key from CCU/Homegear or simulate keypress

    fields:
      address:
        description: Address of homematic device or BidCoS-RF for virtual remote
        example: BidCoS-RF

      channel:
        description: Channel for calling a keypress
        example: 1

      param:
        description: Event to send i.e. PRESS_LONG, PRESS_SHORT
        example: PRESS_LONG

zwave:
  start_network:
    description: Start the zwave network. This might take a while, depending on how big your zwave network is.

  stop_network:
    description: Stop the zwave network, all updates into HASS will stop.

  heal_network:
    description: Start a zwave network heal. This might take a while and will slow down the zwave network greatly while it is being processed. Refer to OZW.log for details.

  add_node:
    description: Add a new node to the zwave network. Refer to OZW.log for details.

  add_node_secure:
    description: Add a new node to the zwave network with secure communications. Node must support this, and network key must be set. Refer to OZW.log for details.

  remove_node:
    description: Remove a node from the zwave network. Refer to OZW.log for details.

  test_network:
    description: This will send test to nodes in the zwave network. This will greatly slow down the zwave network while it is being processed. Refer to OZW.log for details.

  soft_reset:
    description: This will reset the controller without removing its data. Use carefully because not all controllers support this. Refer to controllers manual.

