# Describes the format for available Nest services

snapshot_event:
  name: Take event snapshot
  description: Take a snapshot from a camera for an event.
  target:
    entity:
      integration: nest
      domain: camera
  fields:
    nest_event_id:
      name: Nest Event Id
      description: The nest_event_id from the event to snapshot. Can be populated by an automation trigger for a 'nest_event' with 'data_template'.
      required: true
      selector:
        text:
    filename:
      name: Filename
      description: A filename where the snapshot for the event is written.
      required: true
      example: "/tmp/snapshot_my_camera.jpg"
      selector:
        text:

set_away_mode:
  name: Set away mode
  description: Set the away mode for a Nest structure. For Legacy API.
  fields:
    away_mode:
      name: Away mode
      description: New mode to set.
      required: true
      selector:
        select:
          options:
            - 'away'
            - 'home'
    structure:
      name: Structure
      description: Name(s) of structure(s) to change. Defaults to all structures if not specified.
      example: "Apartment"
      selector:
        object:

set_eta:
  name: Set estimated time of arrival
  description: Set or update the estimated time of arrival window for a Nest structure. For Legacy API.
  fields:
    eta:
      name: ETA
      description: Estimated time of arrival from now.
      required: true
      selector:
        time:
    eta_window:
      name: ETA window
      description: Estimated time of arrival window.
      default: "00:01"
      selector:
        time:
    trip_id:
      name: Trip ID
      description: Unique ID for the trip. Default is auto-generated using a timestamp.
      example: "Leave Work"
      selector:
        text:
    structure:
      name: Structure
      description: Name(s) of structure(s) to change. Defaults to all structures if not specified.
      example: "Apartment"
      selector:
        object:

cancel_eta:
  name: Cancel ETA
  description: Cancel an existing estimated time of arrival window for a Nest structure. For Legacy API.
  fields:
    trip_id:
      name: Trip ID
      description: Unique ID for the trip.
      required: true
      example: "Leave Work"
      selector:
        text:
    structure:
      name: Structure
      description: Name(s) of structure(s) to change. Defaults to all structures if not specified.
      example: "Apartment"
      selector:
        object:
