refresh_library:
  description: Refresh a Plex library to scan for new and updated media.
  fields:
    server_name:
      description: Name of a Plex server if multiple Plex servers configured.
      example: "My Plex Server"
    library_name:
      description: Name of the Plex library to refresh.
      example: "TV Shows"

scan_for_clients:
  description: Scan for available clients from the Plex server(s), local network, and plex.tv.
