# Describes the format for available component services

virtualkey:
  description: Press a virtual key from CCU/Homegear or simulate keypress.
  fields:
    address:
      description: Address of homematic device or BidCoS-RF for virtual remote.
      example: BidCoS-RF
    channel:
      description: Channel for calling a keypress.
      example: 1
    param:
      description: Event to send i.e. PRESS_LONG, PRESS_SHORT.
      example: PRESS_LONG
    interface:
      description: (Optional) for set a hosts value.
      example: Hosts name from config

set_variable_value:
  description: Set the name of a node.
  fields:
    entity_id:
      description: Name(s) of homematic central to set value.
      example: 'homematic.ccu2'
    name:
      description: Name of the variable to set.
      example: 'testvariable'
    value:
      description: New value
      example: 1

set_device_value:
  description: Set a device property on RPC XML interface.
  fields:
    address:
      description: Address of homematic device or BidCoS-RF for virtual remote
      example: BidCoS-RF
    channel:
      description: Channel for calling a keypress
      example: 1
    param:
      description: Event to send i.e. PRESS_LONG, PRESS_SHORT
      example: PRESS_LONG
    interface:
      description: (Optional) for set a hosts value
      example: Hosts name from config
    value:
      description: New value
      example: 1

reconnect:
  description: Reconnect to all Homematic Hubs.
